.\"
.\" Written 2011 by David Herrmann
.\" Dedicated to the Public Domain
.\"
.TH "MISC" 3 "August 2011" "David Herrmann" "Miscellaneous Helper Libraries"
.SH NAME
misc \- Miscellaneous Helper Libraries and Snippet Repository

.SH DESCRIPTION
The following libraries and snippets are part of this repository:

.B libsfs
is a library that helps working with sysfs. It provides convenient helpers to
find devices in /sys and correctly parse common attributes. See
.B ./libsfs/README
for more information on the library.

.B libcstr
is a library with support for binary c strings that may contain
binary-zero-characters. See
.B ./libcstr/man3/cstr.3
for more information.

.B libuconf
is a library that reads and writes recursive configuration files. It has support
for human readable ASCII config files and also binary config files with small
memory footprint. It can read from several formats into the same data structure
and hence allows to switch between different config files but always using the
same API. See
.B ./libuconf/README
for more information.

.B liblmath
is a linear math helper library which is created for maximal compatibility with
OpenGL applications. See
.B ./liblmath/README
for more information.

.SH BUGS
No known bugs. See each library for further details.

.SH AUTHOR
David Herrmann <dh.herrmann@googlemail.com>
