#
# Written 2011 by David Herrmann
# Dedicated to the Public Domain
#

# to be built
LIBNAME=libcstr
C_SRC=cstr.c
C_INC=libcstr.h

# to be installed
INC_I=libcstr.h
MAN_I=$(notdir $(wildcard man3/*.3))

DEPENDS=../inc.makefile
include ../inc.makefile
