#
# Written 2011 by David Herrmann
# Dedicated to the Public Domain
#

# to be built
LIBNAME=liblmath
C_SRC=vector.c matrix.c
C_INC=liblmath.h
LIBS=m

# to be installed
INC_I=liblmath.h

DEPENDS=../inc.makefile
include ../inc.makefile
