.\"
.\" Written 2011 by David Herrmann
.\" Dedicated to the Public Domain
.\"
.TH "MISC" 3 "August 2011" "David Herrmann" "Miscellaneous Helper Libraries"
.SH NAME
misc \- Miscellaneous Helper Libraries and Snippet Repository

.SH DESCRIPTION
The following libraries and snippets are part of this repository:

.B libsfs
is a library that helps working with sysfs. It provides convenient helpers to
find devices in /sys and correctly parse common attributes. See
.BR sfs (3)
for more information on the library.

.SH BUGS
No known bugs. See each library for further details.

.SH AUTHOR
David Herrmann <dh.herrmann@googlemail.com>

.SH "SEE ALSO"
.BR sfs (3)
