.\"
.\" Written 2011 by David Herrmann
.\" Dedicated to the Public Domain
.\"
.TH "CSTR_LEN" 3 "August 2011" "David Herrmann" "CSTR Library"
.SH NAME
CSTR_LEN, CSTR_CHAR, CSTR_VOID, CSTR_UINT8 \- Return array length and buffer of
cstr object

.SH SYNOPSIS
.B #include <libcstr.h>

#define
.B CSTR(str)
CSTR_CHAR(str)
.br
#define
.B CSTR_LEN(str)
((str)->len)
.br
#define
.B CSTR_CHAR(str)
((char*)((str)->buf))
.br
#define
.B CSTR_VOID(str)
((void*)((str)->buf))
.br
#define
.B CSTR_UINT8(str)
((uint8_t*)((str)->buf))

.SH DESCRIPTION
.B CSTR_LEN
returns the length of a cstr object.
.B CSTR_CHAR, CSTR_VOID
and
.B CSTR_UINT8
return a pointer to the actual array converter to the requested pointer type. It
is not required to use these macros. You may also access the structure of the
cstr object directly. See
.BR cstr (3).

.SH AUTHOR
David Herrmann <dh.herrmann@googlemail.com>
.SH "SEE ALSO"
.BR cstr (3),
.BR cstr_alloc (3),
.BR cstr_free (3),
.BR cstr_fit (3),
.BR cstr_new (3),
.BR cstr_dup (3),
.BR cstr_cat (3),
